from selenium.webdriver.common.by import By


class CardsLocators:
    CARDS_BUTTON = (By.ID, "cards-overview-index")
    OPEN_NEW_CARD_BUTTON = (By.XPATH, "//a[@href='/cards/application'] ")
    INCREASE_BONUS_CHECKBOX = (By.NAME, "increasedBonusPoints")
    ORDER_BUTTON = (By.XPATH, "//button[@data-ref='85']")
    AMOUNT_FIELD = (By.XPATH, "//input[@name='application.monthlyIncome']")
    FIRST_CHECKBOX = (By.NAME, "condition.creditHistory")
    SECOND_CHECKBOX = (By.NAME, "condition.personalDataProcessing")
    THIRD_CHECKBOX = (By.NAME, "condition.mobileSubscriberDataProcessing")
    SEND_REQUEST = (By.ID, "inspect")
    SUBMIT_BUTTON = (By.XPATH, "//button[text()='Подтвердить']")
    SUCCESS_ALERT = (By.XPATH, "//div[@class='alert alert-success']")
    FRAME = (By.XPATH, "//iframe[@id='confirmation-frame']")
    CHOOSE_OFFICE_SELECTOR = (By.ID, "card-branch")
    ORDER_CARD = (By.ID, "forward")
    CONFIRM_ORDER = (By.ID, "confirm")
    # Локаторы необходимые для второго кейса
    #     GET_CREDIT_BUTTON = (By.CLASS_NAME, "analytics-button")
    #     CONTINUE_BUTTON = (By.XPATH, "//a[@href='/loan-applications/
    #     card-overdraft/details?applicationRef=card-approved']")
    #     TURN_ON_BUTTON = (By.XPATH, '//button[@data-ga-action]')
    #     ONE_CHECHBOX = (By.NAME, 'condition.agreement')
    #     TWO_CHECKBOX = (By.NAME, 'condition.marketingInformation')
    #     THREE_CHECKBOX = (By.NAME, 'condition.autoPayBack')
    #     FOUR_CHECKBOX = (By.NAME, 'condition.personalDataProcessing')
    #     FIVE_CHECKBOX = (By.NAME, 'condition.transferOfRights')
    #     SIX_CHECKBOX = (By.NAME, 'condition.fullCost')
    #     SEVEN_CHECKBOX = (By.NAME, 'condition.additionalServices')
    #     EIGHT_CHECKBOX = (By.NAME, 'condition.creditHistory')
    #     NINE_CHECKBOX = (By.NAME, 'condition.personalTerms')
    SMS = (By.XPATH, "//span[text()='SMS уведомления']")
    BUTTON = (By.ID, "add-card-notification")
    CONFIRM = (By.XPATH, "//button[text()='Подтвердить']")
    WARNING_ALERT = (By.XPATH, "//div[@class='alert alert-warning']")
    DELETE = (By.XPATH, "//button[@data-notification-ref='SMS-79111111111']")
    EMAIL = (By.XPATH, "//span[text()='E-mail уведомления']")
    EMAIL_RADIOBUTTON = (By.XPATH, "//input[@value='EMAIL']")
    CONNECT_BUTTON = (By.ID, "add-card-notification")
    PAY_IN_INTERNET = (By.XPATH, "//span[text()='Оплата в интернете']")
